import { useEffect, useState } from "react";

type Submission = {
  id: number;
  studentName: string;
  studentId: string;
  examName: string;
  course: string;
  submittedAt: string;
  status: string;
  transcript: string;
  recommendedGrade: string;
  video: string;
};

type DownloadState = {
  transcript: boolean;
  grade: boolean;
  video: boolean;
};

const sampleSubmissions: Submission[] = [
  {
    id: 1,
    studentName: "Alex Johnson",
    studentId: "800123456",
    examName: "Oral Examination",
    course: "CIS 484",
    submittedAt: "September 30, 2026 at 2:34 PM",
    status: "Submitted",
    transcript: "alex-johnson-cis484-transcript.txt",
    recommendedGrade: "alex-johnson-cis484-grade.txt",
    video: "alex-johnson-cis484-video.mp4",
  },
  {
    id: 2,
    studentName: "Jordan Smith",
    studentId: "800123457",
    examName: "Oral Examination",
    course: "CIS 484",
    submittedAt: "September 30, 2026 at 3:12 PM",
    status: "Submitted",
    transcript: "jordan-smith-cis484-transcript.txt",
    recommendedGrade: "jordan-smith-cis484-grade.txt",
    video: "jordan-smith-cis484-video.mp4",
  },
];

const emptyDownloadState = (): DownloadState => ({
  transcript: false,
  grade: false,
  video: false,
});

export default function ExamSubmissions() {
  const [submissions, setSubmissions] = useState<Submission[]>([]);
  const [downloads, setDownloads] = useState<
    Record<number, DownloadState>
  >({});

  useEffect(() => {
    const saved = localStorage.getItem("oralExamSubmissions");

    if (!saved) {
      setSubmissions(sampleSubmissions);
    } else {
      try {
        const savedSubmissions = JSON.parse(saved);

        setSubmissions([
          ...sampleSubmissions,
          ...savedSubmissions,
        ]);
      } catch {
        setSubmissions(sampleSubmissions);
      }
    }

    const savedDownloads =
      localStorage.getItem("oralExamDownloads");

    if (savedDownloads) {
      try {
        setDownloads(JSON.parse(savedDownloads));
      } catch {
        setDownloads({});
      }
    }
  }, []);

  const saveDownloads = (
    updated: Record<number, DownloadState>
  ) => {
    setDownloads(updated);

    localStorage.setItem(
      "oralExamDownloads",
      JSON.stringify(updated)
    );
  };

  const createFile = (
    submission: Submission,
    type: "transcript" | "grade" | "video"
  ) => {
    let filename = "";
    let content = "";

    if (type === "transcript") {
      filename = submission.transcript;

      content = `
OralExam AI
============================

Student: ${submission.studentName}
Student ID: ${submission.studentId}
Course: ${submission.course}
Exam: ${submission.examName}

Submitted:
${submission.submittedAt}

============================

Transcript will be generated
by the OralExam AI backend.
`;
    }

    if (type === "grade") {
      filename = submission.recommendedGrade;

      content = `
OralExam AI
============================

Student: ${submission.studentName}
Student ID: ${submission.studentId}
Course: ${submission.course}
Exam: ${submission.examName}

Recommended Grade
============================

The recommended grade will be
generated by the OralExam AI backend.

Professor review is required before
the grade is finalized.
`;
    }

    if (type === "video") {
      filename = submission.video;

      content = `
OralExam AI

Video placeholder for:

Student: ${submission.studentName}
Student ID: ${submission.studentId}
Exam: ${submission.examName}

The actual examination video will
be generated and stored by the
OralExam AI backend.
`;
    }

    const blob = new Blob(
      [content],
      { type: "text/plain" }
    );

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download = filename;

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  const downloadFile = (
    submission: Submission,
    type: "transcript" | "grade" | "video"
  ) => {
    createFile(submission, type);

    const current =
      downloads[submission.id] || emptyDownloadState();

    const updated = {
      ...downloads,
      [submission.id]: {
        ...current,
        [type]: true,
      },
    };

    saveDownloads(updated);
  };

  const downloadAllMaterials = () => {
    submissions.forEach((submission, index) => {
      setTimeout(() => {
        downloadFile(submission, "transcript");

        setTimeout(() => {
          downloadFile(submission, "grade");
        }, 150);

        setTimeout(() => {
          downloadFile(submission, "video");
        }, 300);
      }, index * 500);
    });
  };

  const downloadAllTranscripts = () => {
    submissions.forEach((submission, index) => {
      setTimeout(() => {
        downloadFile(submission, "transcript");
      }, index * 300);
    });
  };

  const downloadAllVideos = () => {
    submissions.forEach((submission, index) => {
      setTimeout(() => {
        downloadFile(submission, "video");
      }, index * 300);
    });
  };

  const downloadAllGrades = () => {
    submissions.forEach((submission, index) => {
      setTimeout(() => {
        downloadFile(submission, "grade");
      }, index * 300);
    });
  };

  const isDownloaded = (
    id: number,
    type: "transcript" | "grade" | "video"
  ) => {
    return downloads[id]?.[type] === true;
  };

  const totalFiles = submissions.length * 3;

  const downloadedFiles = submissions.reduce(
    (total, submission) => {
      const state = downloads[submission.id];

      if (!state) {
        return total;
      }

      return (
        total +
        (state.transcript ? 1 : 0) +
        (state.grade ? 1 : 0) +
        (state.video ? 1 : 0)
      );
    },
    0
  );

  const allDownloaded =
    totalFiles > 0 &&
    downloadedFiles === totalFiles;

  const allTranscriptsDownloaded =
    submissions.length > 0 &&
    submissions.every((submission) =>
      isDownloaded(submission.id, "transcript")
    );

  const allVideosDownloaded =
    submissions.length > 0 &&
    submissions.every((submission) =>
      isDownloaded(submission.id, "video")
    );

  const allGradesDownloaded =
    submissions.length > 0 &&
    submissions.every((submission) =>
      isDownloaded(submission.id, "grade")
    );

  return (
    <div className="professor-dashboard-page">

      <header className="simple-header">

        <div className="logo">
          <span className="logo-icon">◉</span>
          <span>OralExam AI</span>
        </div>

        <a
          href="/professor/dashboard"
          className="dashboard-logout"
        >
          Dashboard
        </a>

      </header>

      <main className="professor-dashboard-content">

        <a
          href="/professor/dashboard"
          className="manage-back-link"
        >
          ← Back to Dashboard
        </a>

        <section className="submission-page-header">

          <div>

            <p className="eyebrow">
              PROFESSOR PORTAL
            </p>

            <h1>
              Student Submissions
            </h1>

            <p>
              Review completed oral examinations and
              download student examination files.
            </p>

          </div>

          <div className="bulk-download-buttons">

            <button
              type="button"
              className={
                allDownloaded
                  ? "bulk-download-button downloaded"
                  : "bulk-download-button primary"
              }
              onClick={downloadAllMaterials}
              disabled={allDownloaded}
            >
              <span>
                {allDownloaded ? "✓" : "📦"}
              </span>

              {allDownloaded
                ? "All Materials Downloaded"
                : "Download All Materials"}
            </button>

            <button
              type="button"
              className={
                allTranscriptsDownloaded
                  ? "bulk-download-button downloaded"
                  : "bulk-download-button"
              }
              onClick={downloadAllTranscripts}
              disabled={allTranscriptsDownloaded}
            >
              <span>
                {allTranscriptsDownloaded ? "✓" : "📄"}
              </span>

              {allTranscriptsDownloaded
                ? "All Transcripts Downloaded"
                : "Download All Transcripts"}
            </button>

            <button
              type="button"
              className={
                allVideosDownloaded
                  ? "bulk-download-button downloaded"
                  : "bulk-download-button"
              }
              onClick={downloadAllVideos}
              disabled={allVideosDownloaded}
            >
              <span>
                {allVideosDownloaded ? "✓" : "🎥"}
              </span>

              {allVideosDownloaded
                ? "All Videos Downloaded"
                : "Download All Videos"}
            </button>

            <button
              type="button"
              className={
                allGradesDownloaded
                  ? "bulk-download-button downloaded"
                  : "bulk-download-button"
              }
              onClick={downloadAllGrades}
              disabled={allGradesDownloaded}
            >
              <span>
                {allGradesDownloaded ? "✓" : "📝"}
              </span>

              {allGradesDownloaded
                ? "All Grades Downloaded"
                : "Download All Grades"}
            </button>

          </div>

        </section>

        <section className="download-progress-card">

          <div className="download-progress-top">

            <div>

              <span className="submission-label">
                DOWNLOAD PROGRESS
              </span>

              <strong>
                {downloadedFiles} of {totalFiles} files
              </strong>

            </div>

            <span className="download-progress-percent">
              {totalFiles > 0
                ? Math.round(
                    (downloadedFiles / totalFiles) * 100
                  )
                : 0}%
            </span>

          </div>

          <div className="download-progress-track">

            <div
              className="download-progress-bar"
              style={{
                width: `${
                  totalFiles > 0
                    ? (downloadedFiles / totalFiles) * 100
                    : 0
                }%`,
              }}
            />

          </div>

          <div className="download-progress-legend">

            <span>📄 Transcripts</span>
            <span>📝 Grades</span>
            <span>🎥 Videos</span>

          </div>

        </section>

        <section className="submission-summary">

          <div className="submission-summary-card">

            <strong>
              {submissions.length}
            </strong>

            <span>
              Total Submissions
            </span>

          </div>

          <div className="submission-summary-card">

            <strong>
              {downloadedFiles}
            </strong>

            <span>
              Files Downloaded
            </span>

          </div>

          <div className="submission-summary-card">

            <strong>
              {totalFiles - downloadedFiles}
            </strong>

            <span>
              Files Remaining
            </span>

          </div>

        </section>

        <div className="dashboard-section-heading">

          <div>

            <p className="eyebrow">
              EXAM RESULTS
            </p>

            <h2>
              Completed Examinations
            </h2>

          </div>

        </div>

        <section className="submission-list">

          {submissions.map((submission) => {

            const transcriptDownloaded =
              isDownloaded(
                submission.id,
                "transcript"
              );

            const gradeDownloaded =
              isDownloaded(
                submission.id,
                "grade"
              );

            const videoDownloaded =
              isDownloaded(
                submission.id,
                "video"
              );

            const everythingDownloaded =
              transcriptDownloaded &&
              gradeDownloaded &&
              videoDownloaded;

            return (
              <article
                className="submission-card"
                key={submission.id}
              >

                <div className="submission-header">

                  <div className="student-avatar">
                    {submission.studentName
                      .charAt(0)
                      .toUpperCase()}
                  </div>

                  <div className="submission-student">

                    <h3>
                      {submission.studentName}
                    </h3>

                    <p>
                      Student ID: {submission.studentId}
                    </p>

                  </div>

                  <span className="submission-status">
                    {submission.status}
                  </span>

                </div>

                <div className="submission-info">

                  <div>

                    <span className="submission-label">
                      EXAM
                    </span>

                    <strong>
                      {submission.course}
                    </strong>

                    <p>
                      {submission.examName}
                    </p>

                  </div>

                  <div>

                    <span className="submission-label">
                      SUBMITTED
                    </span>

                    <strong>
                      {submission.submittedAt}
                    </strong>

                  </div>

                </div>

                <div className="submission-files">

                  <div
                    className={
                      transcriptDownloaded
                        ? "submission-file file-downloaded"
                        : "submission-file"
                    }
                  >

                    <span className="submission-file-icon">
                      📄
                    </span>

                    <div>

                      <strong>
                        Transcript
                      </strong>

                      <small>
                        {submission.transcript}
                      </small>

                      {transcriptDownloaded && (
                        <em>
                          ✓ Downloaded
                        </em>
                      )}

                    </div>

                    <button
                      type="button"
                      className={
                        transcriptDownloaded
                          ? "file-download-button downloaded"
                          : "file-download-button"
                      }
                      onClick={() =>
                        downloadFile(
                          submission,
                          "transcript"
                        )
                      }
                    >
                      {transcriptDownloaded ? "✓" : "↓"}
                    </button>

                  </div>

                  <div
                    className={
                      gradeDownloaded
                        ? "submission-file file-downloaded"
                        : "submission-file"
                    }
                  >

                    <span className="submission-file-icon">
                      📝
                    </span>

                    <div>

                      <strong>
                        Recommended Grade
                      </strong>

                      <small>
                        {submission.recommendedGrade}
                      </small>

                      {gradeDownloaded && (
                        <em>
                          ✓ Downloaded
                        </em>
                      )}

                    </div>

                    <button
                      type="button"
                      className={
                        gradeDownloaded
                          ? "file-download-button downloaded"
                          : "file-download-button"
                      }
                      onClick={() =>
                        downloadFile(
                          submission,
                          "grade"
                        )
                      }
                    >
                      {gradeDownloaded ? "✓" : "↓"}
                    </button>

                  </div>

                  <div
                    className={
                      videoDownloaded
                        ? "submission-file file-downloaded"
                        : "submission-file"
                    }
                  >

                    <span className="submission-file-icon">
                      🎥
                    </span>

                    <div>

                      <strong>
                        Video Recording
                      </strong>

                      <small>
                        {submission.video}
                      </small>

                      {videoDownloaded && (
                        <em>
                          ✓ Downloaded
                        </em>
                      )}

                    </div>

                    <button
                      type="button"
                      className={
                        videoDownloaded
                          ? "file-download-button downloaded"
                          : "file-download-button"
                      }
                      onClick={() =>
                        downloadFile(
                          submission,
                          "video"
                        )
                      }
                    >
                      {videoDownloaded ? "✓" : "↓"}
                    </button>

                  </div>

                </div>

                <div className="submission-footer">

                  <span>
                    {everythingDownloaded
                      ? "✓ All files downloaded"
                      : "Download individual files above"}
                  </span>

                  <button
                    type="button"
                    className={
                      everythingDownloaded
                        ? "download-submission-button downloaded"
                        : "download-submission-button"
                    }
                    onClick={() => {

                      if (!transcriptDownloaded) {
                        downloadFile(
                          submission,
                          "transcript"
                        );
                      }

                      setTimeout(() => {
                        if (!gradeDownloaded) {
                          downloadFile(
                            submission,
                            "grade"
                          );
                        }
                      }, 150);

                      setTimeout(() => {
                        if (!videoDownloaded) {
                          downloadFile(
                            submission,
                            "video"
                          );
                        }
                      }, 300);

                    }}
                    disabled={everythingDownloaded}
                  >

                    <span>
                      {everythingDownloaded
                        ? "✓"
                        : "⬇"}
                    </span>

                    {everythingDownloaded
                      ? "All Files Downloaded"
                      : "Download All Files"}

                  </button>

                </div>

              </article>
            );
          })}

        </section>

      </main>

      <footer className="home-footer">

        <p>
          OralExam AI
        </p>

        <p>
          AI-assisted oral examination platform
        </p>

      </footer>

    </div>
  );
}
